export const accountClasses = {
  page: 'mx-auto w-full max-w-3xl px-5 py-10 sm:px-8',
  header: 'grid gap-2 pb-8',
  title: 'font-display text-2xl font-bold tracking-tight text-foreground',
  lead: 'text-sm text-muted-foreground',
  section: 'grid gap-4 rounded-xl border border-border bg-surface-raised p-5',
  dangerSection: 'grid gap-4 rounded-xl border border-danger/40 bg-surface-raised p-5',
  sectionTitle: 'font-display text-base font-semibold text-foreground',
  sectionHint: 'text-sm text-muted-foreground',
  field: 'grid gap-1.5',
  row: 'flex flex-wrap items-end gap-3',
  definitionList: 'grid gap-2 text-sm',
  definitionRow: 'flex flex-wrap items-baseline justify-between gap-3',
  definitionTerm: 'text-muted-foreground',
  definitionValue: 'font-medium text-foreground',
  error: 'flex items-start gap-2 text-sm text-danger',
  errorText: 'min-w-0',
} as const;
